jobs:
  - job: 'Windows'
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Python35_x86:
          python.version: '3.5'
          python.architecture: 'x86'
        Python35_x64:
          python.version: '3.5'
          python.architecture: 'x64'
        Python36_x86:
          python.version: '3.6'
          python.architecture: 'x86'
        Python36_x64:
          python.version: '3.6'
          python.architecture: 'x64'
        Python37_x86:
          python.version: '3.7'
          python.architecture: 'x86'
        Python37_x64:
          python.version: '3.7'
          python.architecture: 'x64'
        Python38_x86:
          python.version: '3.8'
          python.architecture: 'x86'
        Python38_x64:
          python.version: '3.8'
          python.architecture: 'x64'
        PyPy3:
          python.version: 'pypy3'
          python.architecture: 'x86'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(python.architecture)'
      - script: python -m pip install --upgrade pip setuptools
        displayName: 'Install packaging tools'
      - script: python -m pip install --upgrade codecov
        displayName: 'Install codecov'
      - script: python -m pip install --force-reinstall -r requirements.txt
        displayName: 'Install requirements'
      - script: python -m pip install --force-reinstall -r requirements-tests.txt
        displayName: 'Install tests requirements'
      - script: pytest
        displayName: 'Run tests'
      - script: python -m doctest README.md
        displayName: 'Run doctests'
      - script: python -m codecov -f coverage.xml -X gcov
        condition: succeeded()
        displayName: 'Upload coverage'
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)

  - job: 'MacOS'
    pool:
      vmImage: 'macOS-latest'
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        PyPy3:
          python.version: 'pypy3'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
      - script: python -m pip install --upgrade pip setuptools
        displayName: 'Install packaging tools'
      - script: python -m pip install --upgrade codecov
        displayName: 'Install codecov'
      - script: python -m pip install --force-reinstall -r requirements.txt
        displayName: 'Install requirements'
      - script: python -m pip install --force-reinstall -r requirements-tests.txt
        displayName: 'Install tests requirements'
      - script: pytest
        displayName: 'Run tests'
      - script: python -m doctest README.md
        displayName: 'Run doctests'
      - script: python -m codecov -f coverage.xml -X gcov
        condition: succeeded()
        displayName: 'Upload coverage'
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)
